### ISSUE TITLE
[Bug Runtime] Ghost number

### ISSUE THREAD

**Issue by RedGl0w** [Omega-Numworks/Omega-RPN#2]
When you enter a number and push it to a stack, the number you entered stays in the text-box

**Comment by quentinguidee** [comment]
If someone wants to solve this issue, please solve it first on boricj/numworks-rpn repository!

**Comment by quentinguidee** [comment]
Issue transfered to https://github.com/boricj/numworks-rpn/issues/14

**Comment by boricj** [comment]
I've fixed the bug on my side (also did a way-overdue thorough rework of the RPN app).

**Comment by quentinguidee** [comment]
@boricj Thank you very much 🙏!! I’ll try that this week-end 👌
