### ISSUE TITLE
negative numbers in matrices

### ISSUE THREAD

**Issue by wawachief** [Omega-Numworks/Omega-RPN#4]

**Comment by quentinguidee** [comment]
Thanks for this issue!

But in facts, Omega-RPN is only to fix compatibility issues between RPN and Omega. If you want to give a feature idea to @boricj (the developer of RPN), please submit this issue to his repository (https://github.com/boricj/numworks-rpn). When this feature is implemented on his repo, we'll merge his changes 😉

Thanks 🙏

**Comment by wawachief** [comment]
I tried to type in a matrix in the RPN app. It seems to work except for the negative numbers. When I hit alpha+- for an element, the whole matrix is impacted. How can I put negative numbers in a matrix ?

**Comment by quentinguidee** [comment]
Sorry I can't help you :/ You can ask him on his repository or on our Discord https://discord.gg/hjH3gtd (because @boricj is a member of the Discord, he could help you) 😉

Edit: Transferred upstream: https://github.com/boricj/numworks-rpn/issues/19
