### ISSUE TITLE
Can't store value into an existing variable

### ISSUE THREAD

**Issue by josesa910** [Omega-Numworks/Omega-RPN#8]
Storing a value into an existing variable causes "Syntax error" message. The only way to do this is to delete variable before and then store.

**Comment by quentinguidee** [comment]
Thanks for this issue!

But in fact, Omega-RPN is only here to fix compatibility issues between RPN and Omega. If you want to report a feature idea or a bug to @boricj (the developer of RPN), please submit this issue to his repository (https://github.com/boricj/numworks-rpn). When this feature is implemented on his repo, we'll merge his changes 😉

Thanks 🙏
